name = "Playwright"
uuid = "246d5a2c-e8ad-4f7d-a897-5346511128f4"
authors = ["GenieFramework Team"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
PyCall = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
